### ISSUE TITLE
User related API's not working

### ISSUE THREAD

**Issue by gpadbidri** [snowblindroan/mod_admin_rest#2]
Hi All,

We are using Prosody Latest Version...When we try querying user related information like Get user : GET : "/admin_rest/user/someuser" when connected with an user with ADMIN priviliges., we get the following response : 
            <b>500 Internal Server Error : It broke. Check your error log for more info. </b>
Also Error Log is not helpful.

NOTE : Username is just "someuser" and NOT "somesuer@vhost.com"
<b>Also, MODULE related queries respond as expected,but user related queries FAIL.</b>

Can you help us on this front ? Any  pointers would be great help. Thanks !

**Comment by wltsmrz** [comment]
It's been a long time since I tested this or worked on it. I'd welcome pull requests but probably won't be able to get around to this issue any time soon, unfortunately

**Comment by ghost** [comment]
@gpadbidri I got this working without any issues on https://github.com/varakh/prosody_web_admin_rest

Maybe close this issue? About a year ago. :+1:

**Comment by wltsmrz** [comment]
Thanks for checking @varakh.
