### ISSUE TITLE
What is expected in authorization header?

### ISSUE THREAD

**Issue by ankitgomkale** [snowblindroan/mod_admin_rest#8]
Issuing commands section says:

>  All requests must contain Basic authentication for a user who has administrative privileges.

How to create this authorization header is not clear from the documentation. How do I create this authorization header?

**Comment by alex1702** [comment]
https://paw.cloud/docs/auth/basic-auth
The Header Name is "Authorization:".
very simple and must send with each request.
> HTTP Basic access authentication is one of the easiest authentication methods and it's only safe with a secure SSL/HTTPS connection. The header generated is:
> 

> `Basic {TOKEN}`

> 
> where the {TOKEN} is the base 64 of the username and password separated by a colon. In pseudo-code, it would be:
> 
> `base64(username + ':' + password)`
